name: React Native CI/CD

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'

    - name: Install dependencies
      run: npm install

    - name: Run unit tests
      run: npm test || true

    - name: Build and test Android
      run: |
        # Start an Android emulator in headless mode
        echo "no" | android create avd --force -n test -t android-30 --abi armeabi-v7a
        emulator -avd test -no-window -no-audio -no-skin -no-boot-anim &

        # Wait for emulator to start
        android-wait-for-emulator

        # Unlock the emulator screen
        adb shell input keyevent 82 &

        # Run React Native app on the emulator
        npx react-native run-android

    - name: Build and test iOS
      run: npx react-native run-ios

    - name: Build and test Web
      run: npx react-native run-web

    - name: Check code structure and readability
      run: npm run lint

    - name: React Project Checker
      uses: VictorDanilov/react-project-checker-action@v0.0.1-alpha
