name: React Native CI/CD

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js and Java 8
      uses: actions/setup-node@v4
      with:
        node-version: '20'
    - run: sudo apt-get install -y openjdk-8-jdk
    - run: sudo update-alternatives --set java /usr/lib/jvm/java-8-openjdk-amd64/jre/bin/java
    - run: java -version

    - name: Install dependencies
      run: npm install

    - name: Install Android SDK
      run: |
        export ANDROID_HOME=$HOME/android-sdk
        export PATH=$PATH:$ANDROID_HOME/emulator
        export PATH=$PATH:$ANDROID_HOME/tools
        export PATH=$PATH:$ANDROID_HOME/tools/bin
        export PATH=$PATH:$ANDROID_HOME/platform-tools
        wget https://dl.google.com/android/repository/sdk-tools-linux-4333796.zip
        unzip sdk-tools-linux-4333796.zip -d $ANDROID_HOME
        yes | $ANDROID_HOME/tools/bin/sdkmanager --licenses
        $ANDROID_HOME/tools/bin/sdkmanager "build-tools;30.0.3" "platforms;android-30" "system-images;android-30;google_apis;armeabi-v7a"

    - name: Start Android emulator
      run: |
        echo "no" | avdmanager create avd -n test -k "system-images;android-30;google_apis;armeabi-v7a"
        emulator -avd test -no-window -no-audio -no-skin -no-boot-anim &

    - name: Wait for emulator to start
      run: android-wait-for-emulator

    - name: Unlock the emulator screen
      run: adb shell input keyevent 82

    - name: Build and test Android
      run: npx react-native run-android

    - name: Build and test iOS
      run: npx react-native run-ios

    - name: Build and test Web
      run: npx react-native run-web

    - name: Check code structure and readability
      run: npm run lint

    - name: React Project Checker
      uses: VictorDanilov/react-project-checker-action@v0.0.1-alpha
